SELECT TOP (1000) [FullDateTime]
      ,[ProductCode]
      ,[TransactionNo]
      ,[EmployeeID]
      ,[PromotionID]
      ,[Quantity]
      ,[SalesAmount]
      ,[CostAmount]
  FROM [HappyBakery].[dbo].[FactSales]